spring : 
# DataBase
  h2 : 
    console : 
      enabled : true
      path : /h2-console
  datasource : 
    url : jdbc:h2:~/local
    # url : jdbc:postgresql://ls-9a28cb17870412f007a2398205280133cf82d571.cusegwfp7qso.ap-northeast-2.rds.amazonaws.com:5432/sbb
    driverClassName : org.h2.Driver
    # driverClassName : org.postgresql.Driver
    username : sa
    # username : dbmasteruser
    password : 
    # password : 9:?F,Fn<0[Gfvy9`]N!~EJ}$_b|SY78O

# Email 설정
  mail:
    host : smtp.naver.com
    port : 465
    username : palebluedot920@naver.com
    password : wndnjsWidmd51
    properties :
      mail.smtp.auth : true
      mail.smtp.ssl.enable : true

# JPA
  jpa : 
    properties : 
      hibernate : 
        dialect : org.hibernate.dialect.H2Dialect
        # dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : update
        format_sql : true
        show_sql : true

# logging
logging :
  logback :
    rollingpolicy :
      max-history : 30
      max-file-size : 100MB
      file-name-pattern : ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file :
    name : logs/sbb.log
  pattern : 
    dateformat : yyyy-MM=dd HH:mm:ss.SSS,Asia/Seoul
    
